// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz1o5ZP1r6zgLH03by_s6yaAwJS19j-6g',
    appId: '1:911747064751:web:06e9d8beebd4a22f86455a',
    messagingSenderId: '911747064751',
    projectId: 'taskkeeper-45c63',
    authDomain: 'taskkeeper-45c63.firebaseapp.com',
    storageBucket: 'taskkeeper-45c63.firebasestorage.app',
    measurementId: 'G-KF0CLG19XW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6GGHhbMsGj_-vWdLQKL_XlaAUgKxkm34',
    appId: '1:911747064751:android:dd362f3b1002eaa086455a',
    messagingSenderId: '911747064751',
    projectId: 'taskkeeper-45c63',
    storageBucket: 'taskkeeper-45c63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANHK_ZlxV0N1uvZmILfAdc8Zj0mEWU34g',
    appId: '1:911747064751:ios:61115075380e2c4386455a',
    messagingSenderId: '911747064751',
    projectId: 'taskkeeper-45c63',
    storageBucket: 'taskkeeper-45c63.firebasestorage.app',
    iosBundleId: 'com.example.taskflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANHK_ZlxV0N1uvZmILfAdc8Zj0mEWU34g',
    appId: '1:911747064751:ios:61115075380e2c4386455a',
    messagingSenderId: '911747064751',
    projectId: 'taskkeeper-45c63',
    storageBucket: 'taskkeeper-45c63.firebasestorage.app',
    iosBundleId: 'com.example.taskflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz1o5ZP1r6zgLH03by_s6yaAwJS19j-6g',
    appId: '1:911747064751:web:a832bae2fa57367886455a',
    messagingSenderId: '911747064751',
    projectId: 'taskkeeper-45c63',
    authDomain: 'taskkeeper-45c63.firebaseapp.com',
    storageBucket: 'taskkeeper-45c63.firebasestorage.app',
    measurementId: 'G-EGBD7ZPZWE',
  );
}
